include(FindPackageHandleStandardArgs)

if(CMAKE_SYSTEM_PROCESSOR MATCHES "(x86_64|AMD64|amd64)")
    set(_D3D_ARCH "x64")
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "(i386|i686|X86|x86)")
    set(_D3D_ARCH "x86")
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "(arm64|ARM64|aarch64)")
    set(_D3D_ARCH "arm64")
else()
    set(_D3D_ARCH "x64")
endif()

if(CMAKE_HOST_WIN32)
    file(TO_CMAKE_PATH "$ENV{ProgramFiles\(x86\)}" _PROG_FILES)
    set(_SDK_ROOT "${_PROG_FILES}/Windows Kits/10/bin")
    if(EXISTS "${_SDK_ROOT}")
        file(GLOB _SDK_VERSIONS RELATIVE "${_SDK_ROOT}" "${_SDK_ROOT}/10.*")
        list(SORT _SDK_VERSIONS ORDER DESCENDING)
        foreach(_VERSION ${_SDK_VERSIONS})
            set(_TEST_PATH "${_SDK_ROOT}/${_VERSION}/${_D3D_ARCH}/d3dcompiler_47.dll")
            if(EXISTS "${_TEST_PATH}")
                set(D3DCompiler_DLL_PATH "${_TEST_PATH}" CACHE FILEPATH "Path to d3dcompiler_47.dll")
                break()
            endif()
        endforeach()
    endif()
endif()

find_package_handle_standard_args(D3DCompiler REQUIRED_VARS D3DCompiler_DLL_PATH)