name: Deploy Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
    build-and-deploy-docs:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                submodules: recursive
            
            - name: Install Toolchain Dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y cmake ninja-build doxygen
            
            - name: Configure CMake
              run: cmake -B build -G Ninja

            - name: Build Doxygen Docs
              run: cmake --build build --target docs

            - name: Deploy to GitHib Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                folder: build/docs/html
                branch: gh-pages